module.exports = {
    "H": "Être humain (Un ou plusieurs êtres humains entiers ou amputés d’une partie non vitale (ex : une femme, un homme sans main).",
    "(H)": "Créature mystique d’allure humaine (ex : fantôme, sorcières, fée).",
    "Hd": "Partie externe d’être humain (ex : une jambe).",
    "(Hd)": "Partie externe de (H) (ex : une main d’ange).",
    "A": "Animal",
    "(A)": "Animal mystique, mythologique (ex : licorne)",
    "Ad": "Partie externe d’animal (ex : une oreille de chat)",
    "(Ad)": "Partie de (A) : (ex : une tête de monstre)",
    "Scène A": "Mise en mouvement de personnages animaux (ex : des chats qui grimpent aux arbres)",
    "Scène H": "Mise en mouvement de personnages humain (ex : deux filles qui courent)",
    "Anat": "Anatomie, partie interne du corps humain (ex : poumon, cœur) ",
    "Squel": "Squelette",
    "Sg": "Sang",
    "Radio": "Radiographie",
    "Sex": "Sexuel (ex : un penis)",
    "Elém": "Elément naturel (ex : feu, eau, terre, le ciel)",
    "Frag": "Fragment, forme interminée, fragmentée, objet pas entier (des rochers, un morceau de fer)",
    "Bot": "Botanique, plante et végétaux (ex : fleur, feuille, arbre, plante)",
    "Géo": "Géographie, carte du monde, pays (ex : la mer Noire, Paris, l’Asie)",
    "Pays":" Paysage, référence à l’environnement et la nature (ex : un coucher de soleil, la plage)",
    "Obj": "Objet (ex: une tasse, une voiture, un coussin)",
    "Symb": "Symbole, lettre, chiffres (ex : la lettre B, le symbole €, un emblème)",
    "Abstr": "Abstraction, contenu abstrait (ex : la colère, dieu, amour, le printemps, l’âme)",
    "Sc": "Sciences, domaine scientifique (ex : mitochondrie, cellule)",
    "Alim": "Aliments (ex : pizza, lasagne, frites)",
    "Art": "Artistique (ex : un tableau de Monet)",
    "Arch" : "Architecture, masse imposante inamovible, édifice, statue, fontaines, pont (ex : Notre-Dame de Paris)",
    "Po" : "Position, réponse déterminée par la position de la découpe par rapport à toute la planche (ex : un noyau car c’est au centre de l’image)",
    "Nb" : "Nombre, réponse déterminée par le nombre de tâches (ex : en planche X la personne répond « 10 parties »)",

}